<a href="https://colab.research.google.com/github/R4HUL-ROY/Multimodal_feature_extraction/blob/main/tobaco3482_FASTTEXT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import os
import pathlib

# Download and load fasttext model

In [2]:
pip install fasttext

     |████████████████████████████████| 68 kB 3.2 MB/s 
  Using cached pybind11-2.9.2-py2.py3-none-any.whl (213 kB)
  Created wheel for fasttext: filename=fasttext-0.9.2-cp37-cp37m-linux_x86_64.whl size=3141315 sha256=2bfe54f8a14e6c8a8f5cff61f79584a8f3fe92ce1a161b32f6664021eed04460
  Stored in directory: /root/.cache/pip/wheels/4e/ca/bf/b020d2be95f7641801a6597a29c8f4f19e38f9c02a345bab9b
Successfully built fasttext


In [3]:
import fasttext.util
fasttext.util.download_model('en', if_exists='ignore')  # English
ft = fasttext.load_model('cc.en.300.bin')

In [5]:
a = ft.get_word_vector("another")
# ft.get_word_vector("dkjeri37id20hnd")

# Load the Tobaco dataset

In [8]:
data_root = pathlib.Path('/content/drive/MyDrive/tobaco_OCR/')

print(data_root)
for item in data_root.iterdir():
  print(item)

/content/drive/MyDrive/tobaco_OCR
/content/drive/MyDrive/tobaco_OCR/Resume
/content/drive/MyDrive/tobaco_OCR/Memo
/content/drive/MyDrive/tobaco_OCR/Letter
/content/drive/MyDrive/tobaco_OCR/Report
/content/drive/MyDrive/tobaco_OCR/Email
/content/drive/MyDrive/tobaco_OCR/ADVE
/content/drive/MyDrive/tobaco_OCR/News
/content/drive/MyDrive/tobaco_OCR/Note
/content/drive/MyDrive/tobaco_OCR/Form
/content/drive/MyDrive/tobaco_OCR/Scientific


In [9]:
def get_file_paths_and_labels(data_root):
     text_paths = [str(path) for path in data_root.glob('*/*.txt')]
     labels = [p.split("/")[-2] for p in text_paths]
     return text_paths, labels

text_paths, labels = get_file_paths_and_labels(data_root)
print(text_paths[1:3400:100])
print(labels[1:3400:100])
print(len(text_paths))
print(len(labels))

['/content/drive/MyDrive/tobaco_OCR/Resume/50630631-0632.txt', '/content/drive/MyDrive/tobaco_OCR/Resume/40002609-2610.txt', '/content/drive/MyDrive/tobaco_OCR/Memo/0000168771.txt', '/content/drive/MyDrive/tobaco_OCR/Memo/1003723216_1003723218.txt', '/content/drive/MyDrive/tobaco_OCR/Memo/0000108319.txt', '/content/drive/MyDrive/tobaco_OCR/Memo/0013140948.txt', '/content/drive/MyDrive/tobaco_OCR/Memo/0000391492.txt', '/content/drive/MyDrive/tobaco_OCR/Memo/2022209162.txt', '/content/drive/MyDrive/tobaco_OCR/Letter/50166929-6929.txt', '/content/drive/MyDrive/tobaco_OCR/Letter/10021964.txt', '/content/drive/MyDrive/tobaco_OCR/Letter/ti16310640.txt', '/content/drive/MyDrive/tobaco_OCR/Letter/504789202_504789204.txt', '/content/drive/MyDrive/tobaco_OCR/Letter/ti03840086_0087.txt', '/content/drive/MyDrive/tobaco_OCR/Letter/94002714.txt', '/content/drive/MyDrive/tobaco_OCR/Report/510907182_510907183.txt', '/content/drive/MyDrive/tobaco_OCR/Report/515245506+-5506.txt', '/content/drive/MyDrive

In [10]:
def get_text_from_path(path):    
    with open(path) as f:
        lines = f.readlines()
        lines  = ' '.join(lines)
        f.close()
    return lines

In [11]:
texts = []
c = 0
for this_path in text_paths:
    texts.append(get_text_from_path(this_path))
    print(c, end= " ")
    c += 1

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276 27

In [12]:
df = pd.DataFrame(list(zip(text_paths, texts, labels)),
               columns =['text_path', 'texts', 'data_label'])
df.head()

text_path  \
0  /content/drive/MyDrive/tobaco_OCR/Resume/50521...   
1  /content/drive/MyDrive/tobaco_OCR/Resume/50630...   
2  /content/drive/MyDrive/tobaco_OCR/Resume/40028...   
3  /content/drive/MyDrive/tobaco_OCR/Resume/10150...   
4  /content/drive/MyDrive/tobaco_OCR/Resume/50538...   

                                               texts data_label  
0  \n \n \n \n \n \n \n \n \n \n \n \n \n \n CURR...     Resume  
1  FF Principal investigator/Program Director (La...     Resume  
2  Name:\n Address:\n Date of Birth:\n Place of B...     Resume  
3  \n _ UNIVERSITY OF MIAMI\n CURRICULUM VITAE\n ...     Resume  
4  BIOGRAPHICAL SKETCH\n Provide the following in...     Resume

# Text Preprocessing and spacy

In [14]:
import re
def remove_punctuations(input_str):
    preprocessed_string = re.sub(r'[^\w\s]','', input_str)
    preprocessed_string = preprocessed_string.replace('\n',' ')
    preprocessed_string = re.sub('_', ' ', preprocessed_string)
    preprocessed_string = re.sub(' +', ' ', preprocessed_string)
    return preprocessed_string


In [15]:
## Tokenize, Lemmatize, stopwords removal
import spacy 
import nltk
nlp = spacy.load("en", disable=['parser', 'tagger', 'ner'])
from nltk.corpus import stopwords
nltk.download('stopwords')
stops = stopwords.words("english")

def normalize(comment, lowercase, remove_stopwords):
    if lowercase:
        comment = comment.lower()
    comment = nlp(comment)
    lemmatized = list()
    for word in comment:
        lemma = word.lemma_.strip()
        if lemma:
            if not remove_stopwords or (remove_stopwords and lemma not in stops):
                lemmatized.append(lemma)
    return " ".join(lemmatized)

normalize("counting playing the Home", lowercase=True, remove_stopwords=True) 

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


'count play home'

In [16]:
df['texts'] = [remove_punctuations(i) for i in df['texts']]
df.head()

text_path  \
0  /content/drive/MyDrive/tobaco_OCR/Resume/50521...   
1  /content/drive/MyDrive/tobaco_OCR/Resume/50630...   
2  /content/drive/MyDrive/tobaco_OCR/Resume/40028...   
3  /content/drive/MyDrive/tobaco_OCR/Resume/10150...   
4  /content/drive/MyDrive/tobaco_OCR/Resume/50538...   

                                               texts data_label  
0   CURRICULUM VITAE Collaborating Investigator P...     Resume  
1  FF Principal investigatorProgram Director Last...     Resume  
2  Name Address Date of Birth Place of Birth Educ...     Resume  
3   UNIVERSITY OF MIAMI CURRICULUM VITAE Standard...     Resume  
4  BIOGRAPHICAL SKETCH Provide the following info...     Resume

In [17]:
df['texts'] = [normalize(i, lowercase=True, remove_stopwords=True) for i in df['texts']]
df.head()

text_path  \
0  /content/drive/MyDrive/tobaco_OCR/Resume/50521...   
1  /content/drive/MyDrive/tobaco_OCR/Resume/50630...   
2  /content/drive/MyDrive/tobaco_OCR/Resume/40028...   
3  /content/drive/MyDrive/tobaco_OCR/Resume/10150...   
4  /content/drive/MyDrive/tobaco_OCR/Resume/50538...   

                                               texts data_label  
0  curriculum vita collaborate investigator ptast...     Resume  
1  ff principal investigatorprogram director last...     Resume  
2  name address date birth place birth education ...     Resume  
3  university miami curriculum vita standard form...     Resume  
4  biographical sketch provide follow information...     Resume

In [18]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
df['data_label']= le.fit_transform(df['data_label'])

In [19]:
df.head()

text_path  \
0  /content/drive/MyDrive/tobaco_OCR/Resume/50521...   
1  /content/drive/MyDrive/tobaco_OCR/Resume/50630...   
2  /content/drive/MyDrive/tobaco_OCR/Resume/40028...   
3  /content/drive/MyDrive/tobaco_OCR/Resume/10150...   
4  /content/drive/MyDrive/tobaco_OCR/Resume/50538...   

                                               texts  data_label  
0  curriculum vita collaborate investigator ptast...           8  
1  ff principal investigatorprogram director last...           8  
2  name address date birth place birth education ...           8  
3  university miami curriculum vita standard form...           8  
4  biographical sketch provide follow information...           8

# Train test Split

In [20]:
from sklearn.model_selection import train_test_split
label = df['data_label']
X_train, X_test, y_train, y_test = train_test_split(df['texts'], df['data_label'] , test_size=0.2, random_state = 42)

In [21]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(2785,)
(2785,)
(697,)
(697,)


# padding sequence on train and test dataset seperately


In [22]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences

max_len = 500

In [23]:
tokenizer = Tokenizer(num_words=len(X_train))
tokenizer.fit_on_texts(X_train)

In [24]:
train_sequence = tokenizer.texts_to_sequences(X_train)

In [25]:
train_padded = pad_sequences(
    train_sequence, maxlen = max_len, truncating = "post", padding = "post" 
)

In [26]:
test_sequence = tokenizer.texts_to_sequences(X_test)
test_padded = pad_sequences(
    test_sequence, maxlen = max_len, truncating = "post", padding = "post" 
)

In [27]:
word_index = tokenizer.word_index
len(word_index)

66383

# Create the embedding matrix using fasttext model

In [28]:
num_words = len(word_index) + 1
embedding_matrix = np.zeros((num_words, 300))

for word, i in word_index.items():
    if i < num_words:
        emb_vec = ft.get_word_vector(word)
        if emb_vec is not None:
            embedding_matrix[i] = emb_vec

In [30]:
embedding_matrix.shape

(66384, 300)

# CNN-1D

In [31]:
from keras.models import Sequential
from keras.layers import Embedding, LSTM, Dense, Dropout, Conv1D, GlobalMaxPooling1D, MaxPooling1D
from keras.initializers import Constant
from tensorflow.keras.optimizers import Adam


cnn = Sequential()

cnn.add(
    Embedding(
        num_words,
        300,
        embeddings_initializer = Constant(embedding_matrix),
        trainable = False
    )
)

cnn.add(Dropout(0.2))
cnn.add(Conv1D(filters=100,kernel_size=3,padding='valid',activation='relu',strides=1))
cnn.add(MaxPooling1D())
cnn.add(Conv1D(filters=200,kernel_size=3,padding='valid',activation='relu',strides=1))
cnn.add(MaxPooling1D())
cnn.add(Conv1D(filters=300,kernel_size=3,padding='valid',activation='relu',strides=1))
cnn.add(MaxPooling1D())
cnn.add(Conv1D(filters=512,kernel_size=3,padding='valid',activation='relu',strides=1))
cnn.add(GlobalMaxPooling1D())

cnn.add(Dense(64, activation = 'relu'))
cnn.add(Dropout(0.4))
cnn.add(Dense(10, activation='softmax'))

optimizer = Adam(learning_rate = 1e-3)

cnn.compile(loss="sparse_categorical_crossentropy", optimizer=optimizer, metrics = ["accuracy"])

In [32]:
cnn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, None, 300)         19915200  
                                                                 
 dropout (Dropout)           (None, None, 300)         0         
                                                                 
 conv1d (Conv1D)             (None, None, 100)         90100     
                                                                 
 max_pooling1d (MaxPooling1D  (None, None, 100)        0         
 )                                                               
                                                                 
 conv1d_1 (Conv1D)           (None, None, 200)         60200     
                                                                 
 max_pooling1d_1 (MaxPooling  (None, None, 200)        0         
 1D)                                                    

In [34]:
history = cnn.fit(
    train_padded,
    y_train,
    epochs = 20,
    validation_data = (test_padded, y_test),
    verbose=1,
)

Epoch 1/20
88/88 [==============================] - 54s 618ms/step - loss: 1.8023 - accuracy: 0.3257 - val_loss: 1.5549 - val_accuracy: 0.4864
Epoch 2/20
88/88 [==============================] - 54s 618ms/step - loss: 1.4714 - accuracy: 0.4779 - val_loss: 1.2901 - val_accuracy: 0.5509
Epoch 3/20
88/88 [==============================] - 53s 608ms/step - loss: 1.3143 - accuracy: 0.5454 - val_loss: 1.1141 - val_accuracy: 0.6227
Epoch 4/20
88/88 [==============================] - 53s 607ms/step - loss: 1.0422 - accuracy: 0.6391 - val_loss: 0.9449 - val_accuracy: 0.6743
Epoch 5/20
88/88 [==============================] - 53s 601ms/step - loss: 0.9199 - accuracy: 0.6743 - val_loss: 0.9459 - val_accuracy: 0.6786
Epoch 6/20
88/88 [==============================] - 53s 600ms/step - loss: 0.8674 - accuracy: 0.7002 - val_loss: 0.8383 - val_accuracy: 0.7102
Epoch 7/20
88/88 [==============================] - 53s 604ms/step - loss: 0.7006 - accuracy: 0.7544 - val_loss: 0.8153 - val_accuracy: 0.7274

In [35]:
sequence = tokenizer.texts_to_sequences(X_test)
padded = pad_sequences(sequence, maxlen = max_len, truncating = "post", padding = "post")

In [36]:
y_pred = cnn.predict(padded)

In [37]:
y_pred = [np.argmax(i) for i in y_pred]

In [38]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.7661406025824964


In [39]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))

[[ 26   0   3   1   2   1   5   1   0   1]
 [  2 109   2   3   2   0   1   1   0   0]
 [  1   0  63   3   0   0   0   4   0   2]
 [  0   0   3  80   9   1   2  11   0   7]
 [  0   2  13   7 114   1   1   4   0   6]
 [  1   0   0   0   1  30   1   3   0   2]
 [  1   2   4   1   1   0  21   0   0   1]
 [  1   1   4   7   2   3   0  25   0  13]
 [  0   0   0   0   0   0   0   0  24   1]
 [  2   0   5   0   1   1   0   2   0  42]]
              precision    recall  f1-score   support

           0       0.76      0.65      0.70        40
           1       0.96      0.91      0.93       120
           2       0.65      0.86      0.74        73
           3       0.78      0.71      0.74       113
           4       0.86      0.77      0.81       148
           5       0.81      0.79      0.80        38
           6       0.68      0.68      0.68        31
           7       0.49      0.45      0.47        56
           8       1.00      0.96      0.98        25
           9       0.56     

# Old Code

In [ ]:
from gensim.models.fasttext import FastText
word_tokens = df['text']

# Defining values for parameters
embedding_size = 300
window_size = 5
min_word = 5
down_sampling = 1e-2

fast_Text_model = FastText(word_tokens,
                      size=embedding_size,
                      window=window_size,
                      min_count=min_word,
                      sample=down_sampling,
                      workers = 4,
                      sg=1,
                      iter=100)

In [ ]:
# from gensim.models import Word2Vec
# # Save fastText gensim model
# fast_Text_model.save("model/ft_model_yelp")
# # Load saved gensim fastText model
# fast_Text_model = Word2Vec.load("model/ft_model_yelp")

In [ ]:
# Check word embedding for a perticular word
l = fast_Text_model.wv['rjat']
print(len(l))
print(l)

300
[ 1.28131807e-01  2.43316293e-01 -5.58495462e-01  3.76027226e-01
  8.70122612e-02  9.77523327e-01  5.77322364e-01 -7.14563906e-01
 -4.00593579e-01 -3.93003255e-01  3.30203474e-01  7.78421760e-01
 -4.86062691e-02  4.07951295e-01  2.35373870e-01  4.40351397e-01
  5.07362604e-01  8.71036947e-02  1.90445721e-01  4.08024728e-01
  1.14477903e-01  7.25169837e-01  1.04393411e+00  8.31587195e-01
  1.17216146e+00  7.91793346e-01  9.30116713e-01  8.77907038e-01
 -7.43993163e-01 -3.17819953e-01 -4.53173667e-02 -1.32715344e+00
 -3.00891995e-01 -7.03721225e-01  1.50148153e-01 -6.95131779e-01
  3.92318219e-01 -3.81677210e-01  1.15712035e+00 -6.34374738e-01
 -5.43438673e-01  4.68942642e-01 -4.10695940e-01  3.50514680e-01
  1.77822739e-01  4.08260465e-01 -3.43997926e-01 -3.66054416e-01
 -1.49861097e-01 -1.19773135e-01 -8.55028629e-05  1.12735033e+00
 -1.21784516e-01  3.70789021e-01 -7.07294941e-01  3.97301108e-01
  1.89165771e-01 -1.30255699e+00  4.38193828e-01  1.25644302e+00
  7.19696760e-01  1.4

In [ ]:
def vectorize_str(token_list):
    embedd = []
    for word in token_list:
        embedd.append(fast_Text_model.wv['word'])

df['text'] = [fast_Text_model.wv[word] for word in df['text']]

Path  \
0  /content/drive/MyDrive/tobaco_OCR/Resume/50521...   
1  /content/drive/MyDrive/tobaco_OCR/Resume/50630...   
2  /content/drive/MyDrive/tobaco_OCR/Resume/40028...   
3  /content/drive/MyDrive/tobaco_OCR/Resume/10150...   
4  /content/drive/MyDrive/tobaco_OCR/Resume/50538...   

                                                text  
0  [curriculum, vita, collaborate, investigator, ...  
1  [ff, principal, investigatorprogram, director,...  
2  [name, address, date, birth, place, birth, edu...  
3  [_, university, miami, curriculum, vita, stand...  
4  [biographical, sketch, provide, follow, inform...

In [ ]:
biglist = []
for this_list in df['text']:
    for i in this_list:
        biglist.append(i)

print(len(biglist))
print(len(set(biglist)))

528520
77684
